baseURL = "https://simasware.com"
languageCode = "en-us"
title = "SimasWare LTD"
#theme = "erblog"
theme = "nix"

[params]
  Name = "Sotiraki Sima"
  HeaderUsername = "root"
  HeaderHostname = "server0"
  About = "Sotiraki Sima, Executive Director in Technology Risk at Goldman Sachs, co-founder of OneFirewall Alliance and former Cyber Security Advisor,  prior to that Sotiraki led the Global Application Security in Barclays Bank PLC. His professional expertise is tracked on automated Security Controls in modern Software Development Lifecycles with particular focus in implementations of DevSecOps practices in big scale organisations."
  ProfilePicture = "Sotiraki-Sima-1.jpg"
  LinkedInID = "sotirakisima"
  GithubID = "simaswareltd"
[menu]
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0
    url = "/"
  [[menu.header]]
    parent = "post"
    name = "Dev-Sec-Ops"
    url = "/Dev-Sec-Ops"
  [[menu.header]]
    parent = "post"
    name = "Secret-Scanner"
    url = "/Secret-Scanner"
  [[menu.header]]
    identifier = "projects"
    name = "projects"
    weight = 0
    url = "/"
  [[menu.header]]
    parent = "projects"
    name = "OneFirewall"
    url = "/onefirewall"
  [[menu.header]]
    parent = "projects"
    name = "OneFirewall-2D-Report"
    url = "/onefirewall-report"
  [[menu.header]]
    parent = "projects"
    name = "OneFirewall-3D-Report"
    url = "/onefirewall-report2"
  [[menu.header]]
    parent = "projects"
    name = "secret-shark"
    url = "/secret-shark"
  [[menu.header]]
    parent = "projects"
    name = "vuln-app"
    url = "/vuln-app"

